version: '3.8'
services:
  app:
    build: .
    container_name: graphql_node
    ports:
      - "4000:4000"
    volumes:
      - ./:/home/graphql/app
    stdin_open: true
    tty: true
    command: tail -f /dev/null
